Trix.config.lang =
  bold: "Жирный"
  bullets: "Список"
  byte:  "Байт"
  bytes: "Байтов"
  captionPlaceholder: "Добавьте подпись"
  code: "Код"
  heading1: "Заголовок"
  indent: "Увеличить уровень"
  italic: "Курсив"
  link: "Ссылка"
  numbers: "Номера"
  outdent: "Уменьшить уровень"
  quote: "Цитата"
  redo: "Повторить"
  remove: "Удалить"
  strike: "Перечеркнутый"
  undo: "Отменить"
  unlink: "Отменить"
  urlPlaceholder: "Вставьте ссылку…"
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"
